import type { ReturnLine } from "$lib/types";

export const sampleLines: ReturnLine[] = [
	{
		volumeNumber: 2,
		pageNumber: 117,
		editor: "tsb",
		heading: true,
		headingText: "داستان رستم و سهراب",
		numberWithinPage: 1,
		hemistichOne: {},
		hemistichTwo: {},
	},
	{
		volumeNumber: 2,
		pageNumber: 117,
		editor: "tsb",
		heading: false,
		numberWithinPage: 2,
		hemistichOne: { text: "اگر تندبادی برآید ز کنج", hasNotes: false },
		hemistichTwo: { text: "به خاک افگند نارسیده ترنج", hasNotes: true },
	},
	{
		volumeNumber: 2,
		pageNumber: 117,
		editor: "tsb",
		heading: false,
		numberWithinPage: 3,
		hemistichOne: { text: "ستمگاره خوانیمش ار دادگر", hasNotes: true },
		hemistichTwo: { text: "هنرمند گوییمش ار بی‌هنر", hasNotes: true },
	},
	{
		volumeNumber: 2,
		pageNumber: 117,
		editor: "tsb",
		heading: false,
		numberWithinPage: 4,
		hemistichOne: { text: "اگر مرگ دادست بیداد چیست", hasNotes: false },
		hemistichTwo: { text: "ز داد این همه بانگ و فریاد چیست", hasNotes: true },
	},
	{
		volumeNumber: 2,
		pageNumber: 117,
		editor: "tsb",
		heading: false,
		numberWithinPage: 5,
		hemistichOne: { text: "ازین راز جان تو آگاه نیست", hasNotes: false },
		hemistichTwo: { text: "بدین پرده اندر ترا راه نیست", hasNotes: true },
	},
	{
		volumeNumber: 2,
		pageNumber: 117,
		editor: "tsb",
		heading: false,
		numberWithinPage: 6,
		numberListed: 5,
		hemistichOne: { text: "همه تا در آز رفته فراز", hasNotes: false },
		hemistichTwo: { text: "به کس بر نشد این در راز باز", hasNotes: true },
	},
	{
		volumeNumber: 2,
		pageNumber: 118,
		editor: "tsb",
		heading: false,
		numberWithinPage: 1,
		hemistichOne: { text: "به رفتن مگر بهتر آیدت جای", hasNotes: true },
		hemistichTwo: { text: "چو آرام گیری به دیگر سرای", hasNotes: true },
	},
	{
		volumeNumber: 2,
		pageNumber: 118,
		editor: "tsb",
		heading: true,
		headingText: "آغاز داستان",
		numberWithinPage: 2,
		hemistichOne: {},
		hemistichTwo: {},
	},
	{
		volumeNumber: 2,
		pageNumber: 118,
		editor: "tsb",
		heading: false,
		numberWithinPage: 3,
		hemistichOne: { text: "ز گفتار دهقان یکی داستان", hasNotes: false },
		hemistichTwo: { text: "بپیوندم از گفتهٔ باستان", hasNotes: true },
	},
	{
		volumeNumber: 2,
		pageNumber: 119,
		editor: "tsb",
		heading: false,
		numberWithinPage: 1,
		hemistichOne: { text: "ز موبد برین گونه برداشت یاد", hasNotes: true },
		hemistichTwo: { text: "که یک روز رستم هم از بامداد", hasNotes: true },
	},
	{
		volumeNumber: 2,
		pageNumber: 119,
		editor: "tsb",
		heading: false,
		numberWithinPage: 2,
		hemistichOne: { text: "غمی بد دلش ساز نخچیر کرد", hasNotes: true },
		hemistichTwo: { text: "کمر بست و ترکش پر از تیر کرد", hasNotes: false },
	},
	{
		volumeNumber: 2,
		pageNumber: 119,
		editor: "tsb",
		heading: false,
		numberWithinPage: 3,
		numberListed: 10,
		hemistichOne: { text: "چو نزدیکی مرز توران رسید", hasNotes: true },
		hemistichTwo: { text: "بیابان سراسر پر از گور دید", hasNotes: false },
	},
	{
		volumeNumber: 2,
		pageNumber: 119,
		editor: "tsb",
		heading: false,
		numberWithinPage: 4,
		hemistichOne: { text: "برافروخت چون گل رخ تاج‌بخش", hasNotes: false },
		hemistichTwo: { text: "بخندید و ز جای برکند رخش", hasNotes: true },
	},
	{
		volumeNumber: 2,
		pageNumber: 119,
		editor: "tsb",
		heading: false,
		numberWithinPage: 5,
		hemistichOne: { text: "به تیر و کمان و به گرز و کمند", hasNotes: false },
		hemistichTwo: { text: "بیفگند بر دشت نخچیر چند", hasNotes: true },
	},
	{
		volumeNumber: 2,
		pageNumber: 119,
		editor: "tsb",
		heading: false,
		numberWithinPage: 6,
		hemistichOne: { text: "ز خاشاک و از خار و شاخ درخت", hasNotes: true },
		hemistichTwo: { text: "یکی آتشی برفروزید سخت", hasNotes: false },
	},
	{
		volumeNumber: 2,
		pageNumber: 119,
		editor: "tsb",
		heading: false,
		numberWithinPage: 7,
		hemistichOne: { text: "چو آتش پراگنده شد پیلتن", hasNotes: false },
		hemistichTwo: { text: "درختی بجست از در بابزن", hasNotes: true },
	},
	{
		volumeNumber: 2,
		pageNumber: 119,
		editor: "tsb",
		heading: false,
		numberWithinPage: 8,
		numberListed: 15,
		hemistichOne: { text: "یکی ترّه‌گوری بزد بر درخت", hasNotes: false },
		hemistichTwo: { text: "که در چنگ او پرّ مرغی نسخت", hasNotes: true },
	},
	{
		volumeNumber: 2,
		pageNumber: 119,
		editor: "tsb",
		heading: false,
		numberWithinPage: 9,
		hemistichOne: { text: "چو بریان شد از هم بکند و بخورد", hasNotes: false },
		hemistichTwo: { text: "ز مغر استخوانش برآورد گرد", hasNotes: false },
	},
	{
		volumeNumber: 2,
		pageNumber: 119,
		editor: "tsb",
		heading: false,
		numberWithinPage: 10,
		hemistichOne: { text: "بخفت و برآسود از روزگار", hasNotes: false },
		hemistichTwo: { text: "چمان و چران رخش در مرغزار", hasNotes: true },
	},
	{
		volumeNumber: 2,
		pageNumber: 119,
		editor: "tsb",
		heading: false,
		numberWithinPage: 11,
		hemistichOne: { text: "سواران ترکان تنی هفت هشت", hasNotes: true },
		hemistichTwo: { text: "بر آن دشت نخچیرگان برگذشت", hasNotes: true },
	},
	{
		volumeNumber: 2,
		pageNumber: 119,
		editor: "tsb",
		heading: false,
		numberWithinPage: 12,
		hemistichOne: { text: "پی اسپ دیدند در مرغزار", hasNotes: true },
		hemistichTwo: { text: "بگشتند گرد لب جویبار", hasNotes: true },
	},
	{
		volumeNumber: 2,
		pageNumber: 119,
		editor: "tsb",
		heading: false,
		numberWithinPage: 13,
		numberListed: 20,
		hemistichOne: { text: "چو بر دشت مر رخش را یافتند", hasNotes: true },
		hemistichTwo: { text: "سوی بند کردنش بشتافتند", hasNotes: false },
	},
];
