import type { ReturnLine } from "$lib/types";

export const sampleLines: ReturnLine[] = [
	{
		volumeNumber: 2,
		pageNumber: 117,
		editor: "tsb",
		heading: true,
		headingText: "داستان رستم و سهراب",
		numberWithinPage: 1,
		hemistichOne: {},
		hemistichTwo: {},
	},
	{
		volumeNumber: 2,
		pageNumber: 117,
		editor: "tsb",
		heading: false,
		numberWithinPage: 2,
		hemistichOne: { text: "اگر تندبادی برآید ز کنج", hasNotes: false },
		hemistichTwo: { text: "به خاک افگند نارسیده ترنج", hasNotes: true },
	},
	{
		volumeNumber: 2,
		pageNumber: 117,
		editor: "tsb",
		heading: false,
		numberWithinPage: 3,
		hemistichOne: { text: "ستمگاره خوانیمش ار دادگر", hasNotes: true },
		hemistichTwo: { text: "هنرمند گوییمش ار بی‌هنر", hasNotes: true },
	},
	{
		volumeNumber: 2,
		pageNumber: 117,
		editor: "tsb",
		heading: false,
		numberWithinPage: 4,
		hemistichOne: { text: "اگر مرگ دادست بیداد چیست", hasNotes: false },
		hemistichTwo: { text: "ز داد این همه بانگ و فریاد چیست", hasNotes: true },
	},
	{
		volumeNumber: 2,
		pageNumber: 117,
		editor: "tsb",
		heading: false,
		numberWithinPage: 5,
		hemistichOne: { text: "ازین راز جان تو آگاه نیست", hasNotes: false },
		hemistichTwo: { text: "بدین پرده اندر ترا راه نیست", hasNotes: true },
	},
	{
		volumeNumber: 2,
		pageNumber: 117,
		editor: "tsb",
		heading: false,
		numberWithinPage: 6,
		numberListed: 5,
		hemistichOne: { text: "همه تا در آز رفته فراز", hasNotes: false },
		hemistichTwo: { text: "به کس بر نشد این در راز باز", hasNotes: true },
	},
	{
		volumeNumber: 2,
		pageNumber: 118,
		editor: "tsb",
		heading: false,
		numberWithinPage: 1,
		hemistichOne: { text: "به رفتن مگر بهتر آیدت جای", hasNotes: true },
		hemistichTwo: { text: "چو آرام گیری به دیگر سرای", hasNotes: true },
	},
	{
		volumeNumber: 2,
		pageNumber: 118,
		editor: "tsb",
		heading: true,
		headingText: "آغاز داستان",
		numberWithinPage: 2,
		hemistichOne: {},
		hemistichTwo: {},
	},
	{
		volumeNumber: 2,
		pageNumber: 118,
		editor: "tsb",
		heading: false,
		numberWithinPage: 3,
		hemistichOne: { text: "ز گفتار دهقان یکی داستان", hasNotes: false },
		hemistichTwo: { text: "بپیوندم از گفتهٔ باستان", hasNotes: true },
	},
	{
		volumeNumber: 2,
		pageNumber: 119,
		editor: "tsb",
		heading: false,
		numberWithinPage: 1,
		hemistichOne: { text: "ز موبد برین گونه برداشت یاد", hasNotes: true },
		hemistichTwo: { text: "که یک روز رستم هم از بامداد", hasNotes: true },
	},
	{
		volumeNumber: 2,
		pageNumber: 119,
		editor: "tsb",
		heading: false,
		numberWithinPage: 2,
		hemistichOne: { text: "غمی بد دلش ساز نخچیر کرد", hasNotes: true },
		hemistichTwo: { text: "کمر بست و ترکش پر از تیر کرد", hasNotes: false },
	},
	{
		volumeNumber: 2,
		pageNumber: 119,
		editor: "tsb",
		heading: false,
		numberWithinPage: 3,
		numberListed: 10,
		hemistichOne: { text: "چو نزدیکی مرز توران رسید", hasNotes: true },
		hemistichTwo: { text: "بیابان سراسر پر از گور دید", hasNotes: false },
	},
	{
		volumeNumber: 2,
		pageNumber: 119,
		editor: "tsb",
		heading: false,
		numberWithinPage: 4,
		hemistichOne: { text: "برافروخت چون گل رخ تاج‌بخش", hasNotes: false },
		hemistichTwo: { text: "بخندید و ز جای برکند رخش", hasNotes: true },
	},
	{
		volumeNumber: 2,
		pageNumber: 119,
		editor: "tsb",
		heading: false,
		numberWithinPage: 5,
		hemistichOne: { text: "به تیر و کمان و به گرز و کمند", hasNotes: false },
		hemistichTwo: { text: "بیفگند بر دشت نخچیر چند", hasNotes: true },
	},
	{
		volumeNumber: 2,
		pageNumber: 119,
		editor: "tsb",
		heading: false,
		numberWithinPage: 6,
		hemistichOne: { text: "ز خاشاک و از خار و شاخ درخت", hasNotes: true },
		hemistichTwo: { text: "یکی آتشی برفروزید سخت", hasNotes: false },
	},
	{
		volumeNumber: 2,
		pageNumber: 119,
		editor: "tsb",
		heading: false,
		numberWithinPage: 7,
		hemistichOne: { text: "چو آتش پراگنده شد پیلتن", hasNotes: false },
		hemistichTwo: { text: "درختی بجست از در بابزن", hasNotes: true },
	},
	{
		volumeNumber: 2,
		pageNumber: 119,
		editor: "tsb",
		heading: false,
		numberWithinPage: 8,
		numberListed: 15,
		hemistichOne: { text: "یکی ترّه‌گوری بزد بر درخت", hasNotes: false },
		hemistichTwo: { text: "که در چنگ او پرّ مرغی نسخت", hasNotes: true },
	},
	{
		volumeNumber: 2,
		pageNumber: 119,
		editor: "tsb",
		heading: false,
		numberWithinPage: 9,
		hemistichOne: { text: "چو بریان شد از هم بکند و بخورد", hasNotes: false },
		hemistichTwo: { text: "ز مغر استخوانش برآورد گرد", hasNotes: false },
	},
	{
		volumeNumber: 2,
		pageNumber: 119,
		editor: "tsb",
		heading: false,
		numberWithinPage: 10,
		hemistichOne: { text: "بخفت و برآسود از روزگار", hasNotes: false },
		hemistichTwo: { text: "چمان و چران رخش در مرغزار", hasNotes: true },
	},
	{
		volumeNumber: 2,
		pageNumber: 119,
		editor: "tsb",
		heading: false,
		numberWithinPage: 11,
		hemistichOne: { text: "سواران ترکان تنی هفت هشت", hasNotes: true },
		hemistichTwo: { text: "بر آن دشت نخچیرگان برگذشت", hasNotes: true },
	},
	{
		volumeNumber: 2,
		pageNumber: 119,
		editor: "tsb",
		heading: false,
		numberWithinPage: 12,
		hemistichOne: { text: "پی اسپ دیدند در مرغزار", hasNotes: true },
		hemistichTwo: { text: "بگشتند گرد لب جویبار", hasNotes: true },
	},
	{
		volumeNumber: 2,
		pageNumber: 119,
		editor: "tsb",
		heading: false,
		numberWithinPage: 13,
		numberListed: 20,
		hemistichOne: { text: "چو بر دشت مر رخش را یافتند", hasNotes: true },
		hemistichTwo: { text: "سوی بند کردنش بشتافتند", hasNotes: false },
	},
	{
		volumeNumber: 2,
		pageNumber: 120,
		editor: "tsb",
		heading: false,
		numberWithinPage: 1,
		hemistichOne: { text: "گرفتند و بردند پویان به شهر", hasNotes: true },
		hemistichTwo: { text: "همی هر یک از رخش جستند بهر", hasNotes: true },
	},
	{
		volumeNumber: 2,
		pageNumber: 120,
		editor: "tsb",
		heading: false,
		numberWithinPage: 2,
		hemistichOne: { text: "چو بیدار شد رستم از خواب خوش", hasNotes: false },
		hemistichTwo: { text: "به کار آمدش بارهٔ دست‌کش", hasNotes: true },
	},
	{
		volumeNumber: 2,
		pageNumber: 120,
		editor: "tsb",
		heading: false,
		numberWithinPage: 3,
		hemistichOne: { text: "غمی گشت چون بارگی را نیافت", hasNotes: true },
		hemistichTwo: { text: "سراسیمه سوی سمنگان شتافت", hasNotes: false },
	},
	{
		volumeNumber: 2,
		pageNumber: 120,
		editor: "tsb",
		heading: false,
		numberWithinPage: 4,
		hemistichOne: { text: "همی گفت کاکنون پیاده نوان", hasNotes: true },
		hemistichTwo: { text: "کجا پویم از ننگ تیره‌روان", hasNotes: true },
	},
	{
		volumeNumber: 2,
		pageNumber: 120,
		editor: "tsb",
		heading: false,
		numberWithinPage: 5,
		numberListed: 25,
		hemistichOne: { text: "ابا ترکش و گرز بسته میان", hasNotes: false },
		hemistichTwo: { text: "چنین ترگ و شمشیر و ببر بیان", hasNotes: true },
	},
	{
		volumeNumber: 2,
		pageNumber: 120,
		editor: "tsb",
		heading: false,
		numberWithinPage: 6,
		hemistichOne: { text: "چه گویند گردان که اسپش که برد", hasNotes: true },
		hemistichTwo: { text: "تهمتن بدانجا بخفت ار بمرد", hasNotes: true },
	},
	{
		volumeNumber: 2,
		pageNumber: 120,
		editor: "tsb",
		heading: false,
		numberWithinPage: 7,
		hemistichOne: { text: "کنون رفت باید به بیچارگی", hasNotes: false },
		hemistichTwo: { text: "به غم دل سپردن به یکبارگی", hasNotes: true },
	},
	{
		volumeNumber: 2,
		pageNumber: 120,
		editor: "tsb",
		heading: false,
		numberWithinPage: 8,
		hemistichOne: { text: "همی بست باید سلیح و کمر", hasNotes: true },
		hemistichTwo: { text: "به جایی نشانش بیابم مگر", hasNotes: true },
	},
	{
		volumeNumber: 2,
		pageNumber: 120,
		editor: "tsb",
		heading: false,
		numberWithinPage: 9,
		hemistichOne: { text: "چو نزدیک شهر سمنگان رسید", hasNotes: false },
		hemistichTwo: { text: "خبر زو به شیر و پلنگان رسید", hasNotes: true },
	},
	{
		volumeNumber: 2,
		pageNumber: 120,
		editor: "tsb",
		heading: false,
		numberWithinPage: 10,
		numberListed: 30,
		hemistichOne: { text: "که آمد پیاده گو تاج‌بخش", hasNotes: false },
		hemistichTwo: { text: "به نخچیرگه زو رمیده‌ست رخش", hasNotes: false },
	},
	{
		volumeNumber: 2,
		pageNumber: 120,
		editor: "tsb",
		heading: false,
		numberWithinPage: 11,
		hemistichOne: { text: "پذیره شدندش بزرگان و شاه", hasNotes: false },
		hemistichTwo: { text: "کسی کو به سر برنهادی کلاه", hasNotes: true },
	},
	{
		volumeNumber: 2,
		pageNumber: 120,
		editor: "tsb",
		heading: false,
		numberWithinPage: 12,
		hemistichOne: { text: "همی گفت هر کس که این رستم است", hasNotes: true },
		hemistichTwo: { text: "وگر آفتاب سپیده‌دم است", hasNotes: true },
	},
	{
		volumeNumber: 2,
		pageNumber: 120,
		editor: "tsb",
		heading: false,
		numberWithinPage: 13,
		hemistichOne: { text: "بدو گفت شاه سمنگان چه بود", hasNotes: true },
		hemistichTwo: { text: "که یارست با تو نبرد آزمود", hasNotes: true },
	},
	{
		volumeNumber: 2,
		pageNumber: 120,
		editor: "tsb",
		heading: false,
		numberWithinPage: 14,
		hemistichOne: { text: "بدین شهر ما نیک‌خواه تویم", hasNotes: true },
		hemistichTwo: { text: "ستوده به فرمان و راه تویم", hasNotes: true },
	},
	{
		volumeNumber: 2,
		pageNumber: 120,
		editor: "tsb",
		heading: false,
		numberWithinPage: 15,
		numberListed: 35,
		hemistichOne: { text: "تن و خواسته زیر فرمان تست", hasNotes: false },
		hemistichTwo: { text: "سر ارجمندان و جان آن تست", hasNotes: true },
	},
	{
		volumeNumber: 2,
		pageNumber: 120,
		editor: "tsb",
		heading: false,
		numberWithinPage: 16,
		hemistichOne: { text: "چو رستم به گفتار او بنگرید", hasNotes: true },
		hemistichTwo: { text: "ز بدها گمانیش کوتاه دید", hasNotes: false },
	},
	{
		volumeNumber: 2,
		pageNumber: 120,
		editor: "tsb",
		heading: false,
		numberWithinPage: 17,
		hemistichOne: { text: "بدو گفت رخشم بدین مرغزار", hasNotes: false },
		hemistichTwo: { text: "ز من دور شد بی لگام و فسار", hasNotes: true },
	},
	{
		volumeNumber: 2,
		pageNumber: 121,
		editor: "tsb",
		heading: false,
		numberWithinPage: 1,
		hemistichOne: { text: "کنون تا سمنگان نشان پی است", hasNotes: false },
		hemistichTwo: { text: "بدان سر کجا جویبار و نی است", hasNotes: true },
	},
	{
		volumeNumber: 2,
		pageNumber: 121,
		editor: "tsb",
		heading: false,
		numberWithinPage: 2,
		hemistichOne: { text: "ترا باشد ار بازجویی سپاس", hasNotes: false },
		hemistichTwo: { text: "بیابد به پاداش نیکی‌شناس", hasNotes: true },
	},
	{
		volumeNumber: 2,
		pageNumber: 121,
		editor: "tsb",
		heading: false,
		numberWithinPage: 3,
		numberListed: 40,
		hemistichOne: { text: "ور ایدونک ماند ز من ناپدید", hasNotes: false },
		hemistichTwo: { text: "سران را بسی سر بباید برید", hasNotes: true },
	},
	{
		volumeNumber: 2,
		pageNumber: 121,
		editor: "tsb",
		heading: false,
		numberWithinPage: 4,
		hemistichOne: { text: "بدو گفت شاه ای سرافراز مرد", hasNotes: false },
		hemistichTwo: { text: "نیارد کسی با تو این کار کرد", hasNotes: true },
	},
	{
		volumeNumber: 2,
		pageNumber: 121,
		editor: "tsb",
		heading: false,
		numberWithinPage: 5,
		hemistichOne: { text: "تو مهمان ما باش و تندی مکن", hasNotes: false },
		hemistichTwo: { text: "به کام تو گردد سراسر سخن", hasNotes: true },
	},
	{
		volumeNumber: 2,
		pageNumber: 121,
		editor: "tsb",
		heading: false,
		numberWithinPage: 6,
		hemistichOne: { text: "یک امشب به می شاد داریم دل", hasNotes: false },
		hemistichTwo: { text: "از اندیشه آزاد داریم دل", hasNotes: true },
	},
	{
		volumeNumber: 2,
		pageNumber: 121,
		editor: "tsb",
		heading: false,
		numberWithinPage: 7,
		hemistichOne: { text: "پی رخش هرگز نماند نهان", hasNotes: false },
		hemistichTwo: { text: "چنان بارهٔ نامور در جهان", hasNotes: true },
	},
	{
		volumeNumber: 2,
		pageNumber: 121,
		editor: "tsb",
		heading: false,
		numberWithinPage: 8,
		numberListed: 45,
		hemistichOne: { text: "تهمتن ز گفتار او شاد شد", hasNotes: false },
		hemistichTwo: { text: "روانش از اندیشه آزاد شد", hasNotes: true },
	},
	{
		volumeNumber: 2,
		pageNumber: 121,
		editor: "tsb",
		heading: false,
		numberWithinPage: 9,
		hemistichOne: { text: "سزا دید رفتن سوی خان او", hasNotes: false },
		hemistichTwo: { text: "به خوبی بیاراست مهمان او", hasNotes: true },
	},
	{
		volumeNumber: 2,
		pageNumber: 121,
		editor: "tsb",
		heading: false,
		numberWithinPage: 10,
		hemistichOne: { text: "سپهبد بدو داد در کاخ جای", hasNotes: false },
		hemistichTwo: { text: "همی بود بر پیش او بر به پای", hasNotes: true },
	},
	{
		volumeNumber: 2,
		pageNumber: 121,
		editor: "tsb",
		heading: false,
		numberWithinPage: 11,
		hemistichOne: { text: "ز شهر و ز لشکر سران را بخواند", hasNotes: false },
		hemistichTwo: { text: "سزاوار با او به شادی نشاند", hasNotes: true },
	},
	{
		volumeNumber: 2,
		pageNumber: 121,
		editor: "tsb",
		heading: false,
		numberWithinPage: 12,
		hemistichOne: { text: "گسارندهٔ باده و رودساز", hasNotes: false },
		hemistichTwo: { text: "سیه‌چشم و گل‌رخ بتان طراز", hasNotes: true },
	},
	{
		volumeNumber: 2,
		pageNumber: 121,
		editor: "tsb",
		heading: false,
		numberWithinPage: 13,
		numberListed: 50,
		hemistichOne: { text: "نشستند با رودسازان بهم", hasNotes: false },
		hemistichTwo: { text: "بدان تا سپهبد نباشد دژم", hasNotes: true },
	},
	{
		volumeNumber: 2,
		pageNumber: 121,
		editor: "tsb",
		heading: false,
		numberWithinPage: 14,
		hemistichOne: { text: "چو شد مست و هنگام خواب آمدش", hasNotes: false },
		hemistichTwo: { text: "همی از نشستن شتاب آمدش", hasNotes: true },
	},
	{
		volumeNumber: 2,
		pageNumber: 122,
		editor: "tsb",
		heading: false,
		numberWithinPage: 1,
		hemistichOne: { text: "سزاوار او جای آرام و خواب", hasNotes: false },
		hemistichTwo: { text: "بیاراست و بنهاد مشک و گلاب", hasNotes: true },
	},
];
