import type { ReturnLine } from "$lib/types";

export const sampleLines: ReturnLine[] = [
	{
		volumeNumber: 2,
		pageNumber: 117,
		numberWithinPage: 1,
		editor: "tsb",
		isHeading: true,
		hasNotes: false,
		headingText: "داستان رستم و سهراب",
	},
	{
		volumeNumber: 2,
		pageNumber: 117,
		numberWithinPage: 2,
		editor: "tsb",
		isHeading: false,
		hasNotes: true,
		hemistichOne: "اگر تندبادی برآید ز کنج",
		hemistichTwo: "به خاک افگند نارسیده ترنج",
	},
	{
		volumeNumber: 2,
		pageNumber: 117,
		numberWithinPage: 3,
		editor: "tsb",
		isHeading: false,
		hasNotes: true,
		hemistichOne: "ستمگاره خوانیمش ار دادگر",
		hemistichTwo: "هنرمند گوییمش ار بی‌هنر",
	},
	{
		volumeNumber: 2,
		pageNumber: 117,
		numberWithinPage: 4,
		editor: "tsb",
		isHeading: false,
		hasNotes: true,
		hemistichOne: "اگر مرگ دادست بیداد چیست",
		hemistichTwo: "ز داد این همه بانگ و فریاد چیست",
	},
	{
		volumeNumber: 2,
		pageNumber: 117,
		numberWithinPage: 5,
		editor: "tsb",
		isHeading: false,
		hasNotes: true,
		hemistichOne: "ازین راز جان تو آگاه نیست",
		hemistichTwo: "بدین پرده اندر ترا راه نیست",
	},
	{
		volumeNumber: 2,
		pageNumber: 117,
		numberWithinPage: 6,
		editor: "tsb",
		isHeading: false,
		hasNotes: true,
		numberListed: 5,
		hemistichOne: "همه تا در آز رفته فراز",
		hemistichTwo: "به کس بر نشد این در راز باز",
	},
	{
		volumeNumber: 2,
		pageNumber: 118,
		numberWithinPage: 1,
		editor: "tsb",
		isHeading: false,
		hasNotes: true,
		hemistichOne: "به رفتن مگر بهتر آیدت جای",
		hemistichTwo: "چو آرام گیری به دیگر سرای",
	},
	{
		volumeNumber: 2,
		pageNumber: 118,
		numberWithinPage: 2,
		editor: "tsb",
		isHeading: true,
		hasNotes: false,
		headingText: "آغاز داستان",
	},
	{
		volumeNumber: 2,
		pageNumber: 118,
		numberWithinPage: 3,
		editor: "tsb",
		isHeading: false,
		hasNotes: true,
		hemistichOne: "ز گفتار دهقان یکی داستان",
		hemistichTwo: "بپیوندم از گفتهٔ باستان",
	},
	{
		volumeNumber: 2,
		pageNumber: 119,
		numberWithinPage: 1,
		editor: "tsb",
		isHeading: false,
		hasNotes: true,
		hemistichOne: "ز موبد برین گونه برداشت یاد",
		hemistichTwo: "که یک روز رستم هم از بامداد",
	},
	{
		volumeNumber: 2,
		pageNumber: 119,
		numberWithinPage: 2,
		editor: "tsb",
		isHeading: false,
		hasNotes: true,
		hemistichOne: "غمی بد دلش ساز نخچیر کرد",
		hemistichTwo: "کمر بست و ترکش پر از تیر کرد",
	},
	{
		volumeNumber: 2,
		pageNumber: 119,
		numberWithinPage: 3,
		editor: "tsb",
		isHeading: false,
		hasNotes: true,
		numberListed: 10,
		hemistichOne: "چو نزدیکی مرز توران رسید",
		hemistichTwo: "بیابان سراسر پر از گور دید",
	},
	{
		volumeNumber: 2,
		pageNumber: 119,
		numberWithinPage: 4,
		editor: "tsb",
		isHeading: false,
		hasNotes: true,
		hemistichOne: "برافروخت چون گل رخ تاج‌بخش",
		hemistichTwo: "بخندید و ز جای برکند رخش",
	},
	{
		volumeNumber: 2,
		pageNumber: 119,
		numberWithinPage: 5,
		editor: "tsb",
		isHeading: false,
		hasNotes: true,
		hemistichOne: "به تیر و کمان و به گرز و کمند",
		hemistichTwo: "بیفگند بر دشت نخچیر چند",
	},
	{
		volumeNumber: 2,
		pageNumber: 119,
		numberWithinPage: 6,
		editor: "tsb",
		isHeading: false,
		hasNotes: true,
		hemistichOne: "ز خاشاک و از خار و شاخ درخت",
		hemistichTwo: "یکی آتشی برفروزید سخت",
	},
	{
		volumeNumber: 2,
		pageNumber: 119,
		numberWithinPage: 7,
		editor: "tsb",
		isHeading: false,
		hasNotes: true,
		hemistichOne: "چو آتش پراگنده شد پیلتن",
		hemistichTwo: "درختی بجست از در بابزن",
	},
	{
		volumeNumber: 2,
		pageNumber: 119,
		numberWithinPage: 8,
		editor: "tsb",
		isHeading: false,
		hasNotes: true,
		numberListed: 15,
		hemistichOne: "یکی ترّه‌گوری بزد بر درخت",
		hemistichTwo: "که در چنگ او پرّ مرغی نسخت",
	},
	{
		volumeNumber: 2,
		pageNumber: 119,
		numberWithinPage: 9,
		editor: "tsb",
		isHeading: false,
		hasNotes: false,
		hemistichOne: "چو بریان شد از هم بکند و بخورد",
		hemistichTwo: "ز مغر استخوانش برآورد گرد",
	},
	{
		volumeNumber: 2,
		pageNumber: 119,
		numberWithinPage: 10,
		editor: "tsb",
		isHeading: false,
		hasNotes: true,
		hemistichOne: "بخفت و برآسود از روزگار",
		hemistichTwo: "چمان و چران رخش در مرغزار",
	},
	{
		volumeNumber: 2,
		pageNumber: 119,
		numberWithinPage: 11,
		editor: "tsb",
		isHeading: false,
		hasNotes: true,
		hemistichOne: "سواران ترکان تنی هفت هشت",
		hemistichTwo: "بر آن دشت نخچیرگان برگذشت",
	},
	{
		volumeNumber: 2,
		pageNumber: 119,
		numberWithinPage: 12,
		editor: "tsb",
		isHeading: false,
		hasNotes: true,
		hemistichOne: "پی اسپ دیدند در مرغزار",
		hemistichTwo: "بگشتند گرد لب جویبار",
	},
	{
		volumeNumber: 2,
		pageNumber: 119,
		numberWithinPage: 13,
		editor: "tsb",
		isHeading: false,
		hasNotes: true,
		numberListed: 20,
		hemistichOne: "چو بر دشت مر رخش را یافتند",
		hemistichTwo: "سوی بند کردنش بشتافتند",
	},
	{
		volumeNumber: 2,
		pageNumber: 120,
		numberWithinPage: 1,
		editor: "tsb",
		isHeading: false,
		hasNotes: true,
		hemistichOne: "گرفتند و بردند پویان به شهر",
		hemistichTwo: "همی هر یک از رخش جستند بهر",
	},
	{
		volumeNumber: 2,
		pageNumber: 120,
		numberWithinPage: 2,
		editor: "tsb",
		isHeading: false,
		hasNotes: true,
		hemistichOne: "چو بیدار شد رستم از خواب خوش",
		hemistichTwo: "به کار آمدش بارهٔ دست‌کش",
	},
	{
		volumeNumber: 2,
		pageNumber: 120,
		numberWithinPage: 3,
		editor: "tsb",
		isHeading: false,
		hasNotes: true,
		hemistichOne: "غمی گشت چون بارگی را نیافت",
		hemistichTwo: "سراسیمه سوی سمنگان شتافت",
	},
	{
		volumeNumber: 2,
		pageNumber: 120,
		numberWithinPage: 4,
		editor: "tsb",
		isHeading: false,
		hasNotes: true,
		hemistichOne: "همی گفت کاکنون پیاده نوان",
		hemistichTwo: "کجا پویم از ننگ تیره‌روان",
	},
	{
		volumeNumber: 2,
		pageNumber: 120,
		numberWithinPage: 5,
		editor: "tsb",
		isHeading: false,
		hasNotes: true,
		numberListed: 25,
		hemistichOne: "ابا ترکش و گرز بسته میان",
		hemistichTwo: "چنین ترگ و شمشیر و ببر بیان",
	},
	{
		volumeNumber: 2,
		pageNumber: 120,
		numberWithinPage: 6,
		editor: "tsb",
		isHeading: false,
		hasNotes: true,
		hemistichOne: "چه گویند گردان که اسپش که برد",
		hemistichTwo: "تهمتن بدانجا بخفت ار بمرد",
	},
	{
		volumeNumber: 2,
		pageNumber: 120,
		numberWithinPage: 7,
		editor: "tsb",
		isHeading: false,
		hasNotes: true,
		hemistichOne: "کنون رفت باید به بیچارگی",
		hemistichTwo: "به غم دل سپردن به یکبارگی",
	},
	{
		volumeNumber: 2,
		pageNumber: 120,
		numberWithinPage: 8,
		editor: "tsb",
		isHeading: false,
		hasNotes: true,
		hemistichOne: "همی بست باید سلیح و کمر",
		hemistichTwo: "به جایی نشانش بیابم مگر",
	},
	{
		volumeNumber: 2,
		pageNumber: 120,
		numberWithinPage: 9,
		editor: "tsb",
		isHeading: false,
		hasNotes: true,
		hemistichOne: "چو نزدیک شهر سمنگان رسید",
		hemistichTwo: "خبر زو به شیر و پلنگان رسید",
	},
	{
		volumeNumber: 2,
		pageNumber: 120,
		numberWithinPage: 10,
		editor: "tsb",
		isHeading: false,
		hasNotes: false,
		numberListed: 30,
		hemistichOne: "که آمد پیاده گو تاج‌بخش",
		hemistichTwo: "به نخچیرگه زو رمیده‌ست رخش",
	},
	{
		volumeNumber: 2,
		pageNumber: 120,
		numberWithinPage: 11,
		editor: "tsb",
		isHeading: false,
		hasNotes: true,
		hemistichOne: "پذیره شدندش بزرگان و شاه",
		hemistichTwo: "کسی کو به سر برنهادی کلاه",
	},
	{
		volumeNumber: 2,
		pageNumber: 120,
		numberWithinPage: 12,
		editor: "tsb",
		isHeading: false,
		hasNotes: true,
		hemistichOne: "همی گفت هر کس که این رستم است",
		hemistichTwo: "وگر آفتاب سپیده‌دم است",
	},
	{
		volumeNumber: 2,
		pageNumber: 120,
		numberWithinPage: 13,
		editor: "tsb",
		isHeading: false,
		hasNotes: true,
		hemistichOne: "بدو گفت شاه سمنگان چه بود",
		hemistichTwo: "که یارست با تو نبرد آزمود",
	},
	{
		volumeNumber: 2,
		pageNumber: 120,
		numberWithinPage: 14,
		editor: "tsb",
		isHeading: false,
		hasNotes: true,
		hemistichOne: "بدین شهر ما نیک‌خواه تویم",
		hemistichTwo: "ستوده به فرمان و راه تویم",
	},
	{
		volumeNumber: 2,
		pageNumber: 120,
		numberWithinPage: 15,
		editor: "tsb",
		isHeading: false,
		hasNotes: true,
		numberListed: 35,
		hemistichOne: "تن و خواسته زیر فرمان تست",
		hemistichTwo: "سر ارجمندان و جان آن تست",
	},
	{
		volumeNumber: 2,
		pageNumber: 120,
		numberWithinPage: 16,
		editor: "tsb",
		isHeading: false,
		hasNotes: true,
		hemistichOne: "چو رستم به گفتار او بنگرید",
		hemistichTwo: "ز بدها گمانیش کوتاه دید",
	},
	{
		volumeNumber: 2,
		pageNumber: 120,
		numberWithinPage: 17,
		editor: "tsb",
		isHeading: false,
		hasNotes: true,
		hemistichOne: "بدو گفت رخشم بدین مرغزار",
		hemistichTwo: "ز من دور شد بی لگام و فسار",
	},
	{
		volumeNumber: 2,
		pageNumber: 121,
		numberWithinPage: 1,
		editor: "tsb",
		isHeading: false,
		hasNotes: true,
		hemistichOne: "کنون تا سمنگان نشان پی است",
		hemistichTwo: "بدان سر کجا جویبار و نی است",
	},
	{
		volumeNumber: 2,
		pageNumber: 121,
		numberWithinPage: 2,
		editor: "tsb",
		isHeading: false,
		hasNotes: true,
		hemistichOne: "ترا باشد ار بازجویی سپاس",
		hemistichTwo: "بیابد به پاداش نیکی‌شناس",
	},
	{
		volumeNumber: 2,
		pageNumber: 121,
		numberWithinPage: 3,
		editor: "tsb",
		isHeading: false,
		hasNotes: true,
		numberListed: 40,
		hemistichOne: "ور ایدونک ماند ز من ناپدید",
		hemistichTwo: "سران را بسی سر بباید برید",
	},
	{
		volumeNumber: 2,
		pageNumber: 121,
		numberWithinPage: 4,
		editor: "tsb",
		isHeading: false,
		hasNotes: true,
		hemistichOne: "بدو گفت شاه ای سرافراز مرد",
		hemistichTwo: "نیارد کسی با تو این کار کرد",
	},
	{
		volumeNumber: 2,
		pageNumber: 121,
		numberWithinPage: 5,
		editor: "tsb",
		isHeading: false,
		hasNotes: true,
		hemistichOne: "تو مهمان ما باش و تندی مکن",
		hemistichTwo: "به کام تو گردد سراسر سخن",
	},
	{
		volumeNumber: 2,
		pageNumber: 121,
		numberWithinPage: 6,
		editor: "tsb",
		isHeading: false,
		hasNotes: true,
		hemistichOne: "یک امشب به می شاد داریم دل",
		hemistichTwo: "از اندیشه آزاد داریم دل",
	},
	{
		volumeNumber: 2,
		pageNumber: 121,
		numberWithinPage: 7,
		editor: "tsb",
		isHeading: false,
		hasNotes: true,
		hemistichOne: "پی رخش هرگز نماند نهان",
		hemistichTwo: "چنان بارهٔ نامور در جهان",
	},
	{
		volumeNumber: 2,
		pageNumber: 121,
		numberWithinPage: 8,
		editor: "tsb",
		isHeading: false,
		hasNotes: true,
		numberListed: 45,
		hemistichOne: "تهمتن ز گفتار او شاد شد",
		hemistichTwo: "روانش از اندیشه آزاد شد",
	},
	{
		volumeNumber: 2,
		pageNumber: 121,
		numberWithinPage: 9,
		editor: "tsb",
		isHeading: false,
		hasNotes: true,
		hemistichOne: "سزا دید رفتن سوی خان او",
		hemistichTwo: "به خوبی بیاراست مهمان او",
	},
	{
		volumeNumber: 2,
		pageNumber: 121,
		numberWithinPage: 10,
		editor: "tsb",
		isHeading: false,
		hasNotes: true,
		hemistichOne: "سپهبد بدو داد در کاخ جای",
		hemistichTwo: "همی بود بر پیش او بر به پای",
	},
	{
		volumeNumber: 2,
		pageNumber: 121,
		numberWithinPage: 11,
		editor: "tsb",
		isHeading: false,
		hasNotes: true,
		hemistichOne: "ز شهر و ز لشکر سران را بخواند",
		hemistichTwo: "سزاوار با او به شادی نشاند",
	},
	{
		volumeNumber: 2,
		pageNumber: 121,
		numberWithinPage: 12,
		editor: "tsb",
		isHeading: false,
		hasNotes: true,
		hemistichOne: "گسارندهٔ باده و رودساز",
		hemistichTwo: "سیه‌چشم و گل‌رخ بتان طراز",
	},
	{
		volumeNumber: 2,
		pageNumber: 121,
		numberWithinPage: 13,
		editor: "tsb",
		isHeading: false,
		hasNotes: true,
		numberListed: 50,
		hemistichOne: "نشستند با رودسازان بهم",
		hemistichTwo: "بدان تا سپهبد نباشد دژم",
	},
	{
		volumeNumber: 2,
		pageNumber: 121,
		numberWithinPage: 14,
		editor: "tsb",
		isHeading: false,
		hasNotes: true,
		hemistichOne: "چو شد مست و هنگام خواب آمدش",
		hemistichTwo: "همی از نشستن شتاب آمدش",
	},
	{
		volumeNumber: 2,
		pageNumber: 122,
		numberWithinPage: 1,
		editor: "tsb",
		isHeading: false,
		hasNotes: true,
		hemistichOne: "سزاوار او جای آرام و خواب",
		hemistichTwo: "بیاراست و بنهاد مشک و گلاب",
	},
];
